name: Copilot Review Integration

on:
  pull_request:
    branches:
      - main
      - develop

  push:
    branches:
      - main
      - develop

jobs:
  copilot_review:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Install necessary dependencies (e.g., Copilot CLI)
      - name: Install Copilot CLI
        run: |
          # Download the Copilot CLI binary
          curl -Lo copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
          chmod +x copilot
          # Move Copilot CLI to a directory in PATH
          sudo mv copilot /usr/local/bin/copilot
          # Verify installation
          copilot --version

      # Run Copilot's `svc deploy` command and capture both stdout and stderr
      - name: Run Copilot Command
        id: copilot_command
        run: |
          echo "Running Copilot svc deploy..."
          result=$(copilot svc deploy --name my-service --env test 2>&1)
          echo "Command output: $result"
          echo "$result" > error_log.txt
          echo "command_result=$result" >> $GITHUB_ENV
          if [[ "$result" == *"error"* ]]; then
            echo "Error found during Copilot command execution!"
            exit 1
          fi

      # Check for any errors and report failure if needed
      - name: Check for Command Errors
        run: |
          if [[ "${{ env.command_result }}" == *"error"* ]]; then
            echo "Error found during Copilot command execution!"
            exit 1
          else:
            echo "Copilot command executed successfully!"

  handle_errors:
    runs-on: ubuntu-latest
    needs: copilot_review
    if: failure() # Only run this job if the previous job fails

    steps:
      - name: Handle Errors
        run: |
          echo "An error occurred during the Copilot command execution process!" | tee error_log.txt
          # Print the error output from the previous job
          echo "Previous job failed with the following error:"
          cat error_log.txt
          # Additional error handling actions like sending notifications can go here